const VENUES = [
  'Lecture Hall 1',
  'Lecture Hall 2',
  'Lecture Hall 3',
  'Lecture Hall 4',
  'Lecture Hall 5',
  'Classroom 1',
  'Classroom 2',
  'Classroom 3',
  'Classroom 4',
  'Classroom 5',
  'GYM Class',
  'Dining Hall',
  'Communication Room',
  'BME Lab',
  'BME Workshop',
  'Computer Lab',
  'Pharmacy Lab',
  'Skills Lab room 1',
  'Skills Lab room 2',
  'Skills Lab room 3',
  'Skills Lab room 4',
  'Skills Lab room 5',
  'Skills Lab room 6',
  'Skills Lab room 7',
  'Skills Lab room 8',
  'Skills Lab room 9',
  'Skills Lab room 10',
  'Main Skills Lab',
  'Any unoccupied Balcony(notify your teacher)',
];

module.exports = VENUES;
