const mongoose = require('mongoose');

const classSchema = new mongoose.Schema({
  name: { 
    type: String, 
    required: true, 
    trim: true 
  },
  description: { 
    type: String,
    maxlength: 8000
  },
  teacher: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  department: {
    type: String,
    required: true,
    trim: true,
  },
  creditsRequired: {
    type: Number,
    min: [0, 'Credits must be a positive number'],
    required: true,
  },
  image: {
    type: String,
    default: '',
  },
  timetable: [{
    day: String,
    startTime: String,
    endTime: String,
    venue: String, // Added venue field
  }],
  venueAnnouncements: [{
    venue: String,
    message: String,
    date: {
      type: Date,
      default: Date.now
    },
    active: {
      type: Boolean,
      default: true
    }
  }],
  enrolledStudents: [{ 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User' 
  }],
  HOD: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User' 
  },
  autoGenerated: {
    type: Boolean,
    default: false,
  },
}, { timestamps: true });

module.exports = mongoose.model('Class', classSchema);
